---
version: 2
multicolumn: false
web-width: 800
export-width: 
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - url: "/users/148228/articles/160725/master/file/figures/Screen%20Shot%202017-03-30%20at%206.43.02%20PM/Screen%20Shot%202017-03-30%20at%206.43.02%20PM.png"
    path: figures/Screen Shot 2017-03-30 at 6.43.02 PM/Screen Shot 2017-03-30 at 6.43.02
      PM.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
